description: Separate audio and video streams from multimedia files, creating
  independent audio-only and video-only outputs for individual processing needs
title: Audio Video Separation
inputs_def:
  - handle: ffmpeg_source
    description: FFmpeg source object containing both audio and video streams to be
      separated
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
outputs_def:
  - handle: only_video
    description: Video-only stream without audio
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
    kind: video
  - handle: only_audio
    description: Audio-only stream without video
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
    kind: audio
icon: ":carbon:partition-specific:"
ui:
  default_width: 350
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
private: true
